### ISSUE TITLE
Activation Bug

### ISSUE THREAD

**Issue by JohnConnor2040** [tormyvancool/TormyVanCool_ReaPack_Scripts#2]
After installing the ULTRASCHALL Library from ReaPack using the provided link: 

https://github.com/tormyvancool/TormyVanCool_ReaPack_Scripts/raw/master/index.xml 

via repository import in Reaper 6.80. It is still unable to activate as a lua script action (ultraschall_Add_Developertools_To_Reaper.lua) 
when running said action, I'm getting an error that says, "cannot open C:\Users\ms-1\AppData\Roaming\REAPER/Scripts/Reaper_Internals/ultraschall_api.lua: No such file or directory" after I load the ultraschall_Add_Developertools_To_Reaper.lua from the Reaper Resource Folder.

![bug](https://github.com/tormyvancool/TormyVanCool_ReaPack_Scripts/assets/134852619/a7c2fd64-27b4-408b-a111-afd5f9cceaa8)
 
![bug2](https://github.com/tormyvancool/TormyVanCool_ReaPack_Scripts/assets/134852619/8f8101aa-b2bd-45d0-a7cc-b92225995924)

**Comment by JohnConnor2040** [comment]
![bug3](https://github.com/tormyvancool/TormyVanCool_ReaPack_Scripts/assets/134852619/0f18264c-ca48-4f08-a86a-0217a6658d91)

**Comment by tormyvancool** [comment]
it's not a bug. It's written that you missed to install the Ultrashall API.

**Comment by JohnConnor2040** [comment]
Oh sorry man. My bad. I`ll get that installed. Please delete that post if
you haven't already and, thanks again for all your hard work!

**Comment by tormyvancool** [comment]
> 

Not problem .. I make also tons of mistakes ... I wanted to update my previous message and I erroneously deleted it.

Yes first install the ultrashall library. In case you have problem with that: you find the owner on the Cockos forum.
Once you installed these repository, then my script works.

This repository is triggering all the required functions, on my script, to correctly perform their job ;-)
